#pragma config(Motor,  port1,           frontLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*-----------------------------------------------------------------------------*/

/*@author Team 5036 - RoboDevils
_________ _______  _______  _______    _______  _______  ______    ______
\__   __/(  ____ \(  ___  )(       )  (  ____ \(  __   )/ ___  \  / ____ \
   ) (   | (    \/| (   ) || () () |  | (    \/| (  )  |\/   \  \( (    \/
   | |   | (__    | (___) || || || |  | (____  | | /   |   ___) /| (____
   | |   |  __)   |  ___  || |(_)| |  (_____ \ | (/ /) |  (___ ( |  ___ \
   | |   | (      | (   ) || |   | |        ) )|   / | |      ) \| (   ) )
   | |   | (____/\| )   ( || )   ( |  /\____) )|  (__) |/\___/  /( (___) )
   )_(   (_______/|/     \||/     \|  \______/ (_______)\______/  \_____/

 _______  _______  ______   _______  ______   _______          _________ _        _______
(  ____ )(  ___  )(  ___ \ (  ___  )(  __  \ (  ____ \|\     /|\__   __/( \      (  ____ \
| (    )|| (   ) || (   ) )| (   ) || (  \  )| (    \/| )   ( |   ) (   | (      | (    \/
| (____)|| |   | || (__/ / | |   | || |   ) || (__    | |   | |   | |   | |      | (_____
|     __)| |   | ||  __ (  | |   | || |   | ||  __)   ( (   ) )   | |   | |      (_____  )
| (\ (   | |   | || (  \ \ | |   | || |   ) || (       \ \_/ /    | |   | |            ) |
| ) \ \__| (___) || )___) )| (___) || (__/  )| (____/\  \   /  ___) (___| (____/\/\____) |
|/   \__/(_______)|/ \___/ (_______)(______/ (_______/   \_/   \_______/(_______/\_______)

*/
/* =============================================================================*/
/*														PROGRAMMER'S NOTES
Motor configuration
						M1 = frontLeft		M2 = frontRight		M3 = backLeft		M4 = backRight
                                 --------------------
                                | M1/            \M2 |
                                |  /              \  |
                                | /                \ |
                                |                    |
                                |                    |
                                | \                / |
                                |  \              /  |
                                | M3\            /M4 |
                                ---------------------
 */

/* =============================================================================*/
//																DEFINING VARIABLES

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*  definitionS and variables for the motor slew rate controller.              */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
/*
#define MOTOR_NUM               kNumbOfTotalMotors
#define MOTOR_MAX_VALUE         127
#define MOTOR_MIN_VALUE         (-127)
#define MOTOR_DEFAULT_SLEW_RATE 10      // Default will cause 375mS from full fwd to rev
#define MOTOR_FAST_SLEW_RATE    256     // essentially off
#define MOTOR_TASK_DELAY        15      // task 1/frequency in mS (about 66Hz)
#define MOTOR_DEADBAND          10

// Array to hold requested speed for the motors
int motorReq[ MOTOR_NUM ];

// Array to hold "slew rate" for the motors, the maximum change every time the task
// runs checking current mootor speed.
int motorSlew[ MOTOR_NUM ];

/* =============================================================================*/
//																	TASKS
/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*  MotorSlewRate      - compares the requested speed of each motor to the     */
/*                       current speed and  increments or decrements to reduce */
/*                       the difference as nesessary                           */
/*-----------------------------------------------------------------------------*/
/*
task MotorSlewRate()
{
    int motorIndex;
    int motorTmp;

    // Initialize stuff
    for(motorIndex=0;motorIndex<MOTOR_NUM;motorIndex++)
        {
        motorReq[motorIndex] = 0;
        motorSlew[motorIndex] = MOTOR_DEFAULT_SLEW_RATE;
        }

    // run task until stopped
    while( true )
        {
        // run loop for every motor
        for( motorIndex=0; motorIndex<MOTOR_NUM; motorIndex++)
            {
            // So we don't keep accessing the internal storage
            motorTmp = motor[ motorIndex ];

            // Do we need to change the motor value ?
            if( motorTmp != motorReq[motorIndex] )
                {
                // increasing motor value
                if( motorReq[motorIndex] > motorTmp )
                    {
                    motorTmp += motorSlew[motorIndex];
                    // limit
                    if( motorTmp > motorReq[motorIndex] )
                        motorTmp = motorReq[motorIndex];
                    }

                // decreasing motor value
                if( motorReq[motorIndex] < motorTmp )
                    {
                    motorTmp -= motorSlew[motorIndex];
                    // limit
                    if( motorTmp < motorReq[motorIndex] )
                        motorTmp = motorReq[motorIndex];
                    }

                // finally set motor
                motor[motorIndex] = motorTmp;
                }
            }

        // Wait approx the speed of motor update over the spi bus
        wait1Msec( MOTOR_TASK_DELAY );
        }

}


/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*  DriveTrain     - reads and maps the vexRT joystick for the x-drive:        */
/*                   		Ch3 (y-axis) => forward/backward movement   					 */
/*                   		Ch4 (x-axis) => side-to-side movement       					 */
/*                   		Ch1 (z-axis) => joystick side-to-side			 					   */
/*-----------------------------------------------------------------------------*/

task DriveTrain(){
	while(true){
		motor[frontLeft] = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
		motor[frontRight] = vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
		motor[backLeft] = vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
		motor[backRight] = vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];
	}

}
/*==============================================================================*/
//																	MAIN
task main(){
	StartTask(DriveTrain);
//	StartTask(MotorSlewRate);
	while( true ){
		wait1Msec(100);
	}

}
